docs: add example and tutorial
zeno-ml/zenoml.com pull request #58
Opened 2024-01-05 12:40 UTC by Sparkier

2024-01-05 16:30 UTC, cabreraalex commented
This is epic!

1. I would move "Examples" and "Tutorials" to be right after "Getting Started" in the sidebar.
2. I wonder what we should name these. I'm thinking "Examples" should maybe be "Use Cases" and "Tutorials" should be "Integrations"? Then we can have a "Tutorials" section that has guides like "how to generate synthetic data"

Otherwise looks awesome, I'll do a copy pass after and merge

2024-01-05 16:31 UTC, cabreraalex requested changes
structure notes

2024-01-06 09:13 UTC, Sparkier commented
> This is epic!
> 
> 1. I would move "Examples" and "Tutorials" to be right after "Getting Started" in the sidebar.
> 2. I wonder what we should name these. I'm thinking "Examples" should maybe be "Use Cases" and "Tutorials" should be "Integrations"? Then we can have a "Tutorials" section that has guides like "how to generate synthetic data"
> 
> Otherwise looks awesome, I'll do a copy pass after and merge

I agree we should have a separate integrations section but this is not really an integration like ragas or Eleuther is I'd say. More like a tutorial how to extract that data IMO.

2024-01-07 20:02 UTC, cabreraalex approved these changes

2024-01-07 20:02 UTC, merged